sentry:
  # Publish all joint states -----------------------------------
  joint_state_controller:
    type: joint_state_controller/JointStateController
    publish_rate: 50
  
  # Position Controllers ---------------------------------------
  # Heading_Left_Front_controller:
  #   type: effort_controllers/JointPositionController
  #   joint: heaing_left_front_joint
  #   pid: {p: 3.0, i: 0.3, d: 10.0}
  # Heading_Right_Front_controller:
  #   type: effort_controllers/JointPositionController
  #   joint: heaing_right_front_joint
  #   pid: {p: 3.0, i: 0.3, d: 10.0}
  # Heading_Left_Back_controller:
  #   type: effort_controllers/JointPositionController
  #   joint: heaing_left_back_joint
  #   pid: {p: 3.0, i: 0.3, d: 10.0}
  # Heading_Right_Back_controller:
  #   type: effort_controllers/JointPositionController
  #   joint: heaing_right_back_joint
  #   pid: {p: 3.0, i: 0.3, d: 10.0}
  Yaw_controller: 
    type: effort_controllers/JointPositionController
    joint: yaw_joint
    pid: {p: 150.0,  d: 0.1, i: 1, i_clamp: 10.0}

    #Velocity Controllers -------------------------------------

  # Driving_Left_Front_controller:
  #   type: effort_controllers/JointVelocityController
  #   joint: driving_left_front_joint
  #   pid: {p: 3.0, i: 0.0, d: 0.3}

  # Driving_Left_Back_controller:
  #   type: effort_controllers/JointVelocityController
  #   joint: driving_left_back_joint
  #   pid: {p: 3.0, i: 0.0, d: 0.3}

  # Driving_Right_Front_controller:
  #   type: effort_controllers/JointVelocityController
  #   joint: driving_right_front_joint
  #   pid: {p: 3.0, i: 0.0, d: 0.3}

  # Driving_Right_Back_controller:
  #   type: effort_controllers/JointVelocityController
  #   joint: driving_right_back_joint
  #   pid: {p: 3.0, i: 0.0, d: 0.3}

